// Copyright 2024-2025 SkeletonEngine

#pragma once

#define SK_VERSION_MAJOR 0
#define SK_VERSION_MINOR 1
#define SK_VERSION_PATCH 5

#define SK_STRINGIFY_HELPER(x) #x
#define SK_VERSION_STRING_IMPL(major, minor, patch) \
  SK_STRINGIFY_HELPER(major) "." SK_STRINGIFY_HELPER(minor) "." SK_STRINGIFY_HELPER(patch)
#define SK_VERSION_STRING SK_VERSION_STRING_IMPL(SK_VERSION_MAJOR, SK_VERSION_MINOR, SK_VERSION_PATCH)
