# GitHub Action to count lines of code on all pushes and pull requests

name: cloc
on: [push, pull_request]
jobs:
  cloc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: scripts/cloc.sh
