# GitHub Action to run cpplint on all pushes and pull requests

name: lint
on: [push, pull_request]
jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - run: pip install cpplint
    - run: scripts/lint/lint-skeleton.sh
    - run: scripts/lint/lint-skeleton-editor.sh
    - run: scripts/lint/lint-skeleton-runtime.sh
